In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/foleyc/Downloads/2020_LoL_esports_match_data_from_OraclesElixir_20200807.csv')

In [5]:
df.info(max_cols=105)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55968 entries, 0 to 55967
Data columns (total 103 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gameid                   55932 non-null  object
 1   datacompleteness         55968 non-null  object
 2   url                      55968 non-null  object
 3   league                   55968 non-null  object
 4   year                     55968 non-null  int64
 5   split                    39720 non-null  object
 6   playoffs                 55968 non-null  int64
 7   date                     55968 non-null  object
 8   game                     55968 non-null  int64
 9   patch                    55968 non-null  float64
 10  playerid                 55968 non-null  int64
 11  side                     55968 non-null  object
 12  position                 55968 non-null  object
 13  player                   46640 non-null  object
 14  team                     55968 non-null  object
 15  champion                 46640 non-null  object
 16  ban1                     54138 non-null  object
 17  ban2                     54180 non-null  object
 18  ban3                     55548 non-null  object
 19  ban4                     54048 non-null  object
 20  ban5                     53886 non-null  object
 21  gamelength               55968 non-null  int64
 22  result                   55968 non-null  int64
 23  kills                    55968 non-null  int64
 24  deaths                   55968 non-null  int64
 25  assists                  55968 non-null  int64
 26  teamkills                55968 non-null  int64
 27  teamdeaths               55968 non-null  int64
 28  doublekills              55728 non-null  float64
 29  triplekills              55728 non-null  float64
 30  quadrakills              55754 non-null  float64
 31  pentakills               55754 non-null  float64
 32  firstblood               54946 non-null  float64
 33  firstbloodkill           46350 non-null  float64
 34  firstbloodassist         46160 non-null  float64
 35  firstbloodvictim         46160 non-null  float64
 36  team kpm                 55968 non-null  float64
 37  ckpm                     55968 non-null  float64
 38  firstdragon              9228 non-null   float64
 39  dragons                  9328 non-null   float64
 40  opp_dragons              9328 non-null   float64
 41  elementaldrakes          9176 non-null   float64
 42  opp_elementaldrakes      9176 non-null   float64
 43  infernals                9176 non-null   float64
 44  mountains                9176 non-null   float64
 45  clouds                   9176 non-null   float64
 46  oceans                   9176 non-null   float64
 47  dragons (type unknown)   4946 non-null   float64
 48  elders                   9234 non-null   float64
 49  opp_elders               9234 non-null   float64
 50  firstherald              9234 non-null   float64
 51  heralds                  9070 non-null   float64
 52  opp_heralds              9070 non-null   float64
 53  firstbaron               8994 non-null   float64
 54  barons                   9328 non-null   float64
 55  opp_barons               9328 non-null   float64
 56  firsttower               9272 non-null   float64
 57  towers                   9328 non-null   float64
 58  opp_towers               9328 non-null   float64
 59  firstmidtower            9222 non-null   float64
 60  firsttothreetowers       9234 non-null   float64
 61  inhibitors               42024 non-null  float64
 62  opp_inhibitors           42024 non-null  float64
 63  damagetochampions        55956 non-null  float64
 64  dpm                      55956 non-null  float64
 65  damageshare              46630 non-null  float64
 66  wardsplaced              55956 non-null  float64
 67  wpm                      55956 non-null  float64
 68  wardskilled              55956 non-null  float64
 69  wcpm                     55956 non-null  float64
 70  controlwardsbought       55956 non-null  float64
 71  visionscore              54744 non-null  float64
 72  vspm                     54744 non-null  float64
 73  totalgold                55968 non-null  int64
 74  earnedgold               55966 non-null  float64
 75  earned gpm               55966 non-null  float64
 76  earnedgoldshare          46640 non-null  float64
 77  goldspent                55728 non-null  float64
 78  gspd                     9288 non-null   float64
 79  total cs                 46844 non-null  float64
 80  minionkills              53390 non-null  float64
 81  monsterkills             55956 non-null  float64
 82  monsterkillsownjungle    55956 non-null  float64
 83  monsterkillsenemyjungle  55956 non-null  float64
 84  cspm                     53402 non-null  float64
 85  goldat10                 55368 non-null  float64
 86  xpat10                   55368 non-null  float64
 87  csat10                   55368 non-null  float64
 88  opp_goldat10             55368 non-null  float64
 89  opp_xpat10               55368 non-null  float64
 90  opp_csat10               55368 non-null  float64
 91  golddiffat10             55368 non-null  float64
 92  xpdiffat10               55368 non-null  float64
 93  csdiffat10               55368 non-null  float64
 94  goldat15                 55332 non-null  float64
 95  xpat15                   55332 non-null  float64
 96  csat15                   55332 non-null  float64
 97  opp_goldat15             55332 non-null  float64
 98  opp_xpat15               55332 non-null  float64
 99  opp_csat15               55332 non-null  float64
 100 golddiffat15             55332 non-null  float64
 101 xpdiffat15               55332 non-null  float64
 102 csdiffat15               55332 non-null  float64
dtypes: float64(75), int64(12), object(16)
memory usage: 44.0+ MB

In [17]:
df.iloc[-10:, :20]

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,playerid,side,position,player,team,champion,ban1,ban2,ban3,ban4
55958,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,3,Blue,mid,Chungy,MAMMOTH,Yasuo,Zoe,LeBlanc,Karma,Orianna
55959,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,4,Blue,bot,Mboma,MAMMOTH,Ashe,Zoe,LeBlanc,Karma,Orianna
55960,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,5,Blue,sup,Artek,MAMMOTH,Braum,Zoe,LeBlanc,Karma,Orianna
55961,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,6,Red,top,Thien,Chiefs Esports Club,Gangplank,Heimerdinger,Volibear,Caitlyn,Nidalee
55962,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,7,Red,jng,Croc,Chiefs Esports Club,Lee Sin,Heimerdinger,Volibear,Caitlyn,Nidalee
55963,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,8,Red,mid,Claire,Chiefs Esports Club,Syndra,Heimerdinger,Volibear,Caitlyn,Nidalee
55964,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,9,Red,bot,Katsurii,Chiefs Esports Club,Senna,Heimerdinger,Volibear,Caitlyn,Nidalee
55965,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,10,Red,sup,Dragku,Chiefs Esports Club,Sett,Heimerdinger,Volibear,Caitlyn,Nidalee
55966,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,100,Blue,team,NaN,MAMMOTH,NaN,Zoe,LeBlanc,Karma,Orianna
55967,ESPORTSTMNT02/1413456,complete,http://matchhistory.na.leagueoflegends.com/en/...,OPL,2020,Split 2,0,2020-08-07 05:58:36,1,10.15,200,Red,team,NaN,Chiefs Esports Club,NaN,Heimerdinger,Volibear,Caitlyn,Nidalee

In [10]:
df_rel = df.iloc[:,[0,11,12,15,22]]

In [11]:
df_rel

                      gameid  side position      champion  result
0      ESPORTSTMNT03/1241318  Blue      top        Rumble       1
1      ESPORTSTMNT03/1241318  Blue      jng         Elise       1
2      ESPORTSTMNT03/1241318  Blue      mid        Qiyana       1
3      ESPORTSTMNT03/1241318  Blue      bot  Miss Fortune       1
4      ESPORTSTMNT03/1241318  Blue      sup      Nautilus       1
...                      ...   ...      ...           ...     ...
55963  ESPORTSTMNT02/1413456   Red      mid        Syndra       0
55964  ESPORTSTMNT02/1413456   Red      bot         Senna       0
55965  ESPORTSTMNT02/1413456   Red      sup          Sett       0
55966  ESPORTSTMNT02/1413456  Blue     team           NaN       1
55967  ESPORTSTMNT02/1413456   Red     team           NaN       0

[55968 rows x 5 columns]

In [ ]:
for game_id in df_rel.gameid.unique():

In [25]:
list_df = df_rel[df_rel.position.isin(['top', 'jng', 'mid', 'bot', 'sup'])].groupby(['gameid', 'side']).champion.apply(lambda x: [y for y in x])

In [41]:
list_df.reset_index(level=[0,1])

,gameid,side,champion
0,5655-7249,Blue,"[Aatrox, Qiyana, Rumble, Senna, Braum]"
1,5655-7249,Red,"[Ornn, Jarvan IV, Ryze, Miss Fortune, Leona]"
2,5655-7250,Blue,"[Aatrox, Qiyana, Orianna, Varus, Braum]"
3,5655-7250,Red,"[Fiora, Jarvan IV, Mordekaiser, Miss Fortune, ..."
4,5655-7251,Blue,"[Ornn, Qiyana, Orianna, Varus, Braum]"
...,...,...,...
9317,ESPORTSTMNT06/1300853,Red,"[Ornn, Wukong, Orianna, Sivir, Karma]"
9318,ESPORTSTMNT06/1300856,Blue,"[Ornn, Lee Sin, Twisted Fate, Aphelios, Blitzc..."
9319,ESPORTSTMNT06/1300856,Red,"[Urgot, Rek'Sai, Galio, Varus, Thresh]"
9320,ESPORTSTMNT06/1300859,Blue,"[Mordekaiser, Graves, Zoe, Aphelios, Nautilus]"
9321,ESPORTSTMNT06/1300859,Red,"[Ornn, Nidalee, Sett, Ashe, Bard]"

In [37]:
processed_df = pd.merge(list_df.reset_index(level=[0,1]), df_rel.loc[:,['gameid', 'side', 'result']], how='left', on=['gameid', 'side'])

In [45]:
processed_df.drop_duplicates(subset=['gameid', 'side', 'result'], inplace=True)

In [46]:
processed_df.columns = ['id', 'team', 'champions', 'win']

In [47]:
processed_df.to_csv('processed_data/')

,id,team,champions,win
0,5655-7249,Blue,"[Aatrox, Qiyana, Rumble, Senna, Braum]",1
6,5655-7249,Red,"[Ornn, Jarvan IV, Ryze, Miss Fortune, Leona]",0
12,5655-7250,Blue,"[Aatrox, Qiyana, Orianna, Varus, Braum]",0
18,5655-7250,Red,"[Fiora, Jarvan IV, Mordekaiser, Miss Fortune, ...",1
24,5655-7251,Blue,"[Ornn, Qiyana, Orianna, Varus, Braum]",1
...,...,...,...,...
55902,ESPORTSTMNT06/1300853,Red,"[Ornn, Wukong, Orianna, Sivir, Karma]",0
55908,ESPORTSTMNT06/1300856,Blue,"[Ornn, Lee Sin, Twisted Fate, Aphelios, Blitzc...",0
55914,ESPORTSTMNT06/1300856,Red,"[Urgot, Rek'Sai, Galio, Varus, Thresh]",1
55920,ESPORTSTMNT06/1300859,Blue,"[Mordekaiser, Graves, Zoe, Aphelios, Nautilus]",0
55926,ESPORTSTMNT06/1300859,Red,"[Ornn, Nidalee, Sett, Ashe, Bard]",1